name: Remote ssh command (for master branch)
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build ET_Wishlist environment development
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: hoadxit/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            whoami
            cd ~/KienBQ/my-proj-fe
            eval `ssh-agent -s`
            ssh-add /root/.ssh/github_key
            git checkout .
            git clean -df
            git pull
            git status
            sudo docker stop FirstProj
            sudo docker rm FirstProj
            sudo docker rmi FirstProj
            sudo docker build -t  FirstProj .
            sudo docker run -d --restart unless-stopped --name FirstProj -p 3030:3000 FirstProj